export class ErrorDetailDTO {
    readonly cod: string;
    readonly name: string;
    readonly type: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */