import { Field, InputType } from "@nestjs/graphql";
import { IsAlpha } from "class-validator";

@InputType()
export class UserTypeDTO {

    @IsAlpha()
    @Field()
    readonly cod: string;
    
    @Field()
    readonly name: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */