import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { ErrorType } from '../entity/error_type.entity';
import { ErrorTypeDTO } from '../entity/error_type.dto';
import { RenderType } from 'src/api/render_type/entity/render_type.entity'

@Injectable()
export class ErrorTypeService extends BasicCrudService<ErrorType, string, ErrorTypeDTO>{

    constructor(
        @InjectRepository(ErrorType)
        protected repo: Repository<ErrorType>,
    ) {super();}

    findById(id: string): Promise<ErrorType>{
        try{
            return this.findOne({where: {cod:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: ErrorTypeDTO): ErrorType{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new ErrorType();
        entity.name = dto.name;
        let render_type = new RenderType();
        render_type.cod = dto.render_type;
        entity.render_type = render_type;
        return entity;
    }

    async dataValidationBeforeCreate(dto: ErrorTypeDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: ErrorType, dto: ErrorTypeDTO): ErrorType{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.cod) throw new Error('Entity id null');

        //Assign data
        entity.name = dto.name ? dto.name : entity.name;
        let render_type = new RenderType();
        render_type.cod = dto.render_type;
        entity.render_type = dto.render_type ? render_type : entity.render_type;
        return entity;
    }

    async dataValidationBeforeEdit(dto: ErrorTypeDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */