import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { UserType } from '../entity/user_type.entity';
import { UserTypeDTO } from '../entity/user_type.dto';

@Injectable()
export class UserTypeService extends BasicCrudService<UserType, string, UserTypeDTO>{

    constructor(
        @InjectRepository(UserType)
        protected repo: Repository<UserType>,
    ) {super();}

    findById(id: string): Promise<UserType>{
        try{
            return this.findOne({where: {cod:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: UserTypeDTO): UserType{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new UserType();
        entity.cod = dto.cod;
        entity.name = dto.name;
        return entity;
    }

    async dataValidationBeforeCreate(dto: UserTypeDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: UserType, dto: UserTypeDTO): UserType{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.cod) throw new Error('Entity id null');

        //Assign data
        entity.name = dto.name ? dto.name : entity.name;
        return entity;
    }

    async dataValidationBeforeEdit(dto: UserTypeDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */