import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { RenderType } from './entity/render_type.entity';
import { RenderTypeService } from './service/render_type.service';
import { RenderTypeController } from './controller/render_type.controller';
import { RenderTypeResolver } from './resolver/render_type.resolver';

@Module({
    imports: [
        TypeOrmModule.forFeature([RenderType]),
    ],
    controllers: [
        RenderTypeController,
    ],
    providers: [
        RenderTypeService,
        RenderTypeResolver,
    ],
    exports: [
        RenderTypeService,
    ],
})
export class RenderTypeModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */