import { Field, InputType } from "@nestjs/graphql";

@InputType()
export class LoomDTO {

    @Field({ nullable: true })
    readonly uuid: string;

    @Field()
    readonly number: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */