import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { Demand } from 'src/api/demand/entity/demand.entity'
import { Field, ObjectType } from '@nestjs/graphql';

@Entity({name:'loom'})
@ObjectType()
export class Loom{

    @PrimaryGeneratedColumn()
    @Field()
    uuid: string;

    @Column()
    @Field()
    number: string;

    @OneToMany(() => Demand, e => e.loom)
    demands: Demand[];

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */