import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { Loom } from '../entity/loom.entity';
import { LoomDTO } from '../entity/loom.dto';
import { LoomService } from '../service/loom.service';

@Controller('loom')
export class LoomController extends BasicRestController<Loom, string, LoomDTO>{

    constructor(protected service: LoomService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */