import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { ErrorDetail } from '../entity/error_detail.entity';
import { ErrorDetailDTO } from '../entity/error_detail.dto';
import { ErrorDetailService } from '../service/error_detail.service';

@Controller('error-detail')
@UseGuards(AuthGuard('jwt'))
export class ErrorDetailController extends BasicRestController<ErrorDetail, string, ErrorDetailDTO>{

    constructor(protected service: ErrorDetailService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */