import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { User } from './entity/users.entity';
import { UserService } from './service/users.service';
import { UserController } from './controller/users.controller';
import { AuthModule } from '../auth/auth.module';
import { UserBusiness } from './service/users.business';

@Module({
    imports: [
        TypeOrmModule.forFeature([User]),
        AuthModule,
    ],
    controllers: [
        UserController,
    ],
    providers: [
        UserService,
        UserBusiness,
    ],
    exports: [
        UserService,
        UserBusiness,
    ],
})
export class UserModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */