import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { User } from './entity/users.entity';
import { UserService } from './service/users.service';
import { UserController } from './controller/users.controller';
import { AuthModule } from '../auth/auth.module';
import { UserBusiness } from './service/users.business';
import { LoginController } from './controller/login.controller';
import { UserResolver } from './resolver/user.resolver';
import { UserTypeModule } from '../user_type/user_type.module';

@Module({
    imports: [
        TypeOrmModule.forFeature([User]),
        AuthModule,
        UserTypeModule,
    ],
    controllers: [
        UserController,
        LoginController,
    ],
    providers: [
        UserService,
        UserBusiness,
        UserResolver,
    ],
    exports: [
        UserService,
        UserBusiness,
    ],
})
export class UserModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */