import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { ErrorType } from '../entity/error_type.entity';
import { ErrorTypeDTO } from '../entity/error_type.dto';
import { ErrorTypeService } from '../service/error_type.service';

@Controller('error-type')
export class ErrorTypeController extends BasicRestController<ErrorType, string, ErrorTypeDTO>{

    constructor(protected service: ErrorTypeService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */