import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { RenderType } from 'src/api/render_type/entity/render_type.entity'
import { ErrorDetail } from 'src/api/error_detail/entity/error_detail.entity'

@Entity({name:'error_type'})
export class ErrorType{

    @PrimaryColumn()
    cod: string;

    @Column()
    name: string;

    @ManyToOne(() => RenderType, e => e.types, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "render_type" })
    render_type: RenderType;

    @OneToMany(() => ErrorDetail, e => e.type)
    types: ErrorDetail[];

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */