import { Field, InputType } from "@nestjs/graphql";

@InputType()
export class ErrorTypeDTO {
    
    @Field()
    readonly cod: string;
    
    @Field()
    readonly name: string;
    
    @Field()
    readonly render_type: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */