export class ErrorTypeDTO {
    readonly cod: string;
    readonly name: string;
    readonly render_type: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */