import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { DemandState } from '../entity/demand_state.entity';
import { DemandStateDTO } from '../entity/demand_state.dto';
import { DemandStateService } from '../service/demand_state.service';

@Controller('demand-state')
export class DemandStateController extends BasicRestController<DemandState, string, DemandStateDTO>{

    constructor(protected service: DemandStateService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */