import { Module } from '@nestjs/common';
import { UserTypeModule } from './user_type/user_type.module';
import { UserModule } from './users/users.module';
import { DemandStateModule } from './demand_state/demand_state.module';
import { DemandModule } from './demand/demand.module';
import { RenderTypeModule } from './render_type/render_type.module';
import { ErrorTypeModule } from './error_type/error_type.module';
import { ErrorDetailModule } from './error_detail/error_detail.module';
import { LoomModule } from './loom/loom.module';

@Module({
    imports: [
        UserTypeModule,
        UserModule,
        DemandStateModule,
        DemandModule,
        RenderTypeModule,
        ErrorTypeModule,
        ErrorDetailModule,
        LoomModule,
    ],
    controllers: [
    ],
    providers: [
    ],
    exports: [
    ],
})
export class ApiModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */