import { Field, InputType } from "@nestjs/graphql";

@InputType()
export class UserDTO {

    @Field()
    readonly uuid: string;
    
    @Field()
    readonly name: string;
    
    @Field()
    readonly login: string;
    
    @Field()
    readonly password: string;
    
    @Field()
    readonly state: number;
    
    @Field()
    readonly type: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */