export class UserDTO {
    readonly uuid: string;
    readonly name: string;
    readonly login: string;
    readonly password: string;
    readonly state: number;
    readonly type: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */