import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { UserType } from '../entity/user_type.entity';
import { UserTypeDTO } from '../entity/user_type.dto';
import { UserTypeService } from '../service/user_type.service';

@Controller('user-type')
export class UserTypeController extends BasicRestController<UserType, string, UserTypeDTO>{

    constructor(protected service: UserTypeService){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */