import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { UserType } from './entity/user_type.entity';
import { UserTypeService } from './service/user_type.service';
import { UserTypeController } from './controller/user_type.controller';
import { UserTypeResolver } from './resolver/user_type.resolver';

@Module({
    imports: [
        TypeOrmModule.forFeature([UserType]),
    ],
    controllers: [
        UserTypeController,
    ],
    providers: [
        UserTypeService,
        UserTypeResolver,
    ],
    exports: [
        UserTypeService,
    ],
})
export class UserTypeModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */