import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { ErrorType } from './entity/error_type.entity';
import { ErrorTypeService } from './service/error_type.service';
import { ErrorTypeController } from './controller/error_type.controller';
import { ErrorTypeResolver } from './resolver/error_type.resolver';
import { RenderTypeModule } from '../render_type/render_type.module';

@Module({
    imports: [
        TypeOrmModule.forFeature([ErrorType]),
        RenderTypeModule,
    ],
    controllers: [
        ErrorTypeController,
    ],
    providers: [
        ErrorTypeService,
        ErrorTypeResolver,
    ],
    exports: [
        ErrorTypeService,
    ],
})
export class ErrorTypeModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */