export class DemandDTO {
    uuid: string;
    readonly warp: string;
    readonly weft_quantity: number;
    readonly date_created: Date;
    date_closed: Date;
    readonly user_create: string;
    readonly user_close: string;
    demand_state: string;
    readonly error_detail: string;
    readonly loom: string;

    bytes: string;
}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */