import { Entity, Column, PrimaryGeneratedColumn, PrimaryColumn, OneToMany, ManyToOne, JoinColumn } from 'typeorm';
import { User } from 'src/api/users/entity/users.entity'
import { DemandState } from 'src/api/demand_state/entity/demand_state.entity'
import { ErrorDetail } from 'src/api/error_detail/entity/error_detail.entity'
import { Loom } from 'src/api/loom/entity/loom.entity'

@Entity({name:'demand'})
export class Demand{

    @PrimaryGeneratedColumn()
    uuid: string;

    @Column()
    warp: string;

    @Column()
    weft_quantity: number;

    @Column()
    date_created: Date;

    @Column()
    date_closed: Date;

    @ManyToOne(() => User, e => e.demands_created, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "user_create" })
    user_create: User;

    @ManyToOne(() => User, e => e.demands_closed, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "user_close" })
    user_close: User;

    @ManyToOne(() => DemandState, e => e.demands, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "demand_state" })
    demand_state: DemandState;

    @ManyToOne(() => ErrorDetail, e => e.demands, {
        onDelete: "CASCADE",
        eager: true,
    })
    @JoinColumn({ name: "error_detail" })
    error_detail: ErrorDetail;

    @Column()
    loom: string;

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */