import { Controller, Get, Post, Body, HttpException, Param, UseGuards, Res, HttpCode, HttpStatus } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { User } from '../entity/users.entity';
import { UserDTO } from '../entity/users.dto';
import { UserBusiness } from '../service/users.business';
import { AuthDTO } from 'src/api/auth/entity/auth.dto';
import { Response } from 'express';

@Controller('users')
@UseGuards(AuthGuard('jwt'))
export class UserController extends BasicRestController<User, string, UserDTO>{

    constructor(protected service: UserBusiness){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */