import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Loom } from './entity/loom.entity';
import { LoomService } from './service/loom.service';
import { LoomController } from './controller/loom.controller';
import { LoomResolver } from './resolver/loom.resolver';

@Module({
    imports: [
        TypeOrmModule.forFeature([Loom]),
    ],
    controllers: [
        LoomController,
    ],
    providers: [
        LoomService,
        LoomResolver,
    ],
    exports: [
        LoomService,
    ],
})
export class LoomModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */