import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Demand } from './entity/demand.entity';
import { DemandService } from './service/demand.service';
import { DemandController } from './controller/demand.controller';
import { DemandBusiness } from './service/demand.business';
import { DemandResolver } from './resolver/demand.resolver';
import { ErrorDetailModule } from '../error_detail/error_detail.module';

@Module({
    imports: [
        TypeOrmModule.forFeature([Demand]),
        ErrorDetailModule,
    ],
    controllers: [
        DemandController,
    ],
    providers: [
        DemandService,
        DemandBusiness,
        DemandResolver,
    ],
    exports: [
        DemandService,
        DemandBusiness,
    ],
})
export class DemandModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */