import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { Demand } from './entity/demand.entity';
import { DemandService } from './service/demand.service';
import { DemandController } from './controller/demand.controller';
import { DemandBusiness } from './service/demand.business';

@Module({
    imports: [
        TypeOrmModule.forFeature([Demand]),
    ],
    controllers: [
        DemandController,
    ],
    providers: [
        DemandService,
        DemandBusiness,
    ],
    exports: [
        DemandService,
        DemandBusiness,
    ],
})
export class DemandModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */