import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import { DemandState } from './entity/demand_state.entity';
import { DemandStateService } from './service/demand_state.service';
import { DemandStateController } from './controller/demand_state.controller';

@Module({
    imports: [
        TypeOrmModule.forFeature([DemandState]),
    ],
    controllers: [
        DemandStateController,
    ],
    providers: [
        DemandStateService,
    ],
    exports: [
        DemandStateService,
    ],
})
export class DemandStateModule{}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */