import { Controller, Get, Post, Body, HttpException, Param, UseGuards } from '@nestjs/common';
import { HttpResponse } from '../../../commons/responses/http_response';
import { BasicRestController } from '../../../commons/controllers/rest.controller';
import { AuthGuard } from '@nestjs/passport';
import { Demand } from '../entity/demand.entity';
import { DemandDTO } from '../entity/demand.dto';
import { DemandBusiness } from '../service/demand.business';

@Controller('demand')
export class DemandController extends BasicRestController<Demand, string, DemandDTO>{

    constructor(protected service: DemandBusiness){super();}

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */