import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { Loom } from '../entity/loom.entity';
import { LoomDTO } from '../entity/loom.dto';

@Injectable()
export class LoomService extends BasicCrudService<Loom, string, LoomDTO>{

    constructor(
        @InjectRepository(Loom)
        protected repo: Repository<Loom>,
    ) {super();}

    findById(id: string): Promise<Loom>{
        try{
            return this.findOne({where: {uuid:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: LoomDTO): Loom{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new Loom();
        entity.number = dto.number;
        return entity;
    }

    async dataValidationBeforeCreate(dto: LoomDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: Loom, dto: LoomDTO): Loom{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.uuid) throw new Error('Entity id null');

        //Assign data
        entity.number = dto.number ? dto.number : entity.number;
        return entity;
    }

    async dataValidationBeforeEdit(dto: LoomDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */