import { Injectable } from '@nestjs/common';
import { BasicCrudService } from '../../../commons/services/crud.service';
import { InjectRepository } from '@nestjs/typeorm';
import { Repository } from 'typeorm';
import { RenderType } from '../entity/render_type.entity';
import { RenderTypeDTO } from '../entity/render_type.dto';

@Injectable()
export class RenderTypeService extends BasicCrudService<RenderType, string, RenderTypeDTO>{

    constructor(
        @InjectRepository(RenderType)
        protected repo: Repository<RenderType>,
    ) {super();}

    findById(id: string): Promise<RenderType>{
        try{
            return this.findOne({where: {cod:id}});
        } catch(err){
            throw new Error(err.message);
        }
    }

    buildBaseCreation(dto: RenderTypeDTO): RenderType{
        //Validations data
        if(! dto) throw new Error('DTO empty');

        //Assign data
        let entity = new RenderType();
        entity.name = dto.name;
        return entity;
    }

    async dataValidationBeforeCreate(dto: RenderTypeDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

    buildBaseEdition(entity: RenderType, dto: RenderTypeDTO): RenderType{
        //Validations data
        if(! dto) throw new Error('DTO empty');
        if(! dto.cod) throw new Error('Entity id null');

        //Assign data
        entity.name = dto.name ? dto.name : entity.name;
        return entity;
    }

    async dataValidationBeforeEdit(dto: RenderTypeDTO): Promise<void> {
        // Input validations for null values that are required
        // For example validate if not exists for specific(s) properties
        // Example same login, same email, same cod, same nit
    }

}

/** Generated by https://github.com/VictorAndres20 code generator for database, NestJS, React */